var i18n = {
    "msgChangeGroup": "The current group information has been modified, Do you want to %s before continue?",
    "msgChangeGeneralTab": "The current group information has been modified, Do you want to continue?",
    "msgNumHabitaciones": "The number of listed rooms, %s the number of rooms requested. Do you want to update the initially requested information?",
    "msgExceeds": "exceeds",
    "msgLess": "is less than",
    "btnCancel": "Cancel",
    "btnOk":"Yes",
    "btnReload": "Load original data",
    "btnDiscardChanges": "Discard changes",
    "btnSaveGroup":"Save group",
    "btnform-group": "recalculate the rate",
    "btnrates": "recalculate the rate",
    "btnform-group-info": "save group",
    "btnpays": "save the payment scheme",
};